pipeline {
    agent any
    stages {
        stage('Hello from docker') {
            agent {
                docker {
                    image 'python'
                }
            }
            steps {
                sh 'python hello.py'
            }
        }
    }
}

